# Generated by Django 4.2.2 on 2023-06-29 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price_per_scoop', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantity_available', models.IntegerField(default=40)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='OrderFlavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0)),
                ('flavor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glacier.flavor')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='glacier.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='flavors',
            field=models.ManyToManyField(through='glacier.OrderFlavor', to='glacier.flavor'),
        ),
    ]
